Reading from: data/data-cleaned/behavior-data/2019-Oct-cleaned.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_000.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_001.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_002.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_003.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_004.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_005.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_006.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_007.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_008.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_009.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_010.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_011.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_012.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_013.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_014.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_015.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_016.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_017.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_018.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_019.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_020.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_021.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_022.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_023.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_024.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_025.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_026.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_027.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_028.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_029.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_030.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_031.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_032.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_033.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_034.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_035.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_036.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_037.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_038.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_039.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_040.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_041.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_042.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_043.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_044.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_045.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_046.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_047.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_048.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_049.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_050.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_051.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_052.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_053.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_054.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_055.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_056.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_057.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_058.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_059.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_060.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_061.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_062.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_063.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_064.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_065.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_066.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_067.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_068.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_069.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_070.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_071.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_072.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_073.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_074.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_075.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_076.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_077.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_078.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_079.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_080.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_081.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_082.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_083.csv
✅ Saved chunk: data/data-chunks/oct/part_chunk_084.csv

📋 COPY Commands for Supabase (run in psql):

\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_000.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_001.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_002.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_003.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_004.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_005.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_006.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_007.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_008.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_009.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_010.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_011.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_012.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_013.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_014.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_015.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_016.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_017.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_018.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_019.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_020.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_021.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_022.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_023.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_024.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_025.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_026.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_027.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_028.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_029.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_030.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_031.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_032.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_033.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_034.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_035.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_036.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_037.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_038.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_039.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_040.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_041.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_042.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_043.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_044.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_045.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_046.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_047.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_048.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_049.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_050.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_051.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_052.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_053.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_054.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_055.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_056.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_057.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_058.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_059.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_060.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_061.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_062.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_063.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_064.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_065.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_066.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_067.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_068.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_069.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_070.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_071.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_072.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_073.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_074.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_075.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_076.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_077.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_078.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_079.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_080.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_081.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_082.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_083.csv' WITH (FORMAT csv, HEADER true);
\COPY user_behavior_oct (event_time, event_type, product_id, category_id, category_code, brand, price, user_id, user_session, event_date, event_hour, day_of_week, main_category, event_dayofweek, event_month, event_day) FROM '/Users/vakho/Desktop/DataAnalysis/ecommerce-user-behavior-project/data/data-chunks/oct/part_chunk_084.csv' WITH (FORMAT csv, HEADER true);

✅ All done.
